version: '3.8'

# services:
#   bbl_interview:
#     container_name: bbl_interview
#     network_mode: host
#     build:
#       context: .
#     environment:
#       - DATABASE_URL=sqlserver://localhost:1433;database=bblInterview;user=sa;password=bbl@12345;trustServerCertificate=true

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: bbl@12345
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  
  bbl_interview:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - sql_server
    environment:
      DATABASE_URL: sqlserver://sql_server:1433;database=bblInterview;user=sa;password=bbl@12345;trustServerCertificate=true
